<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Hosting - Azure Application Insights for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2015, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Azure Application Insights for Orchard Core: This Orchard Core module enables easy integration of Azure Application Insights telemetry into Orchard. Just install the module, configure the instrumentation key from a configuration source, and collected data will start appearing in the Azure Portal. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Azure;ApplicationInsights;Analytics;Telemetry;Monitoring;LombiqHostingSuite</PackageTags>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Azure-Application-Insights</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Azure-Application-Insights</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <!-- Using a beta version is necessary until 3.0.2 is out, because 3.0.1 imports System.Linq.Async and so wrecks any
         IAsyncEnumerable-using code that references this project. -->
    <PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="3.0.2-beta1">
      <!-- This is needed to include the Uploader component (TraceUpload.zip) in the publish output folder, and thus
      deploy it to the server too. See:
      https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/issues/241#issuecomment-3706178984. -->
      <PrivateAssets>analyzers;build</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OrchardCore.Media.Azure" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.0-preview-18924" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.3.osoe-925" />
  </ItemGroup>

</Project>
